### ISSUE TITLE
Can I make it work on server side with an api?

### ISSUE THREAD

**Issue by arthuryeti** [heysailor/meteor-accounts-facebook-accessToken#1]
Hi,

I'm trying to use your package on the server side, but I don't know which method I should use.

Thanks

**Comment by heysailor** [comment]
The sole purpose of this package is to handle the transfer of an accessToken from the client to the server for login. It hooks into the Meteor Facebook package to do the login.

Get Outlook for iOS

On Tue, Jun 14, 2016 at 9:50 PM +1000, "Arthur" notifications@github.com wrote:

Hi,

I'm trying to use your package on the server side, but I don't know which method I should use.

Thanks
